python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 2 --handles 1 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 3 --handles 1 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 3 --handles 2 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 4 --handles 2 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 4 --handles 3 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 5 --handles 2 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 5 --handles 3 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 5 --handles 4 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 6 --handles 2 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 6 --handles 3 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 6 --handles 4 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 6 --handles 5 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 7 --handles 4 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 7 --handles 5 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 7 --handles 6 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 8 --handles 5 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 8 --handles 6 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 8 --handles 7 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 9 --handles 5 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 9 --handles 6 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 9 --handles 7 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 9 --handles 8 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 10 --handles 6 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 10 --handles 7 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 10 --handles 8 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 10 --handles 9 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 11 --handles 4 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 11 --handles 5 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 11 --handles 6 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 11 --handles 7 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 11 --handles 8 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 11 --handles 9 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 11 --handles 10 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 12 --handles 8 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 12 --handles 9 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 12 --handles 10 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 12 --handles 11 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 13 --handles 4 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 13 --handles 5 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 13 --handles 6 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 13 --handles 7 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 13 --handles 8 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 13 --handles 9 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 13 --handles 10 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 13 --handles 11 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 13 --handles 12 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 14 --handles 7 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 14 --handles 10 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 14 --handles 11 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 14 --handles 12 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 14 --handles 13 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 15 --handles 10 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 15 --handles 11 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 15 --handles 12 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 15 --handles 13 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 15 --handles 14 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 16 --handles 12 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 16 --handles 13 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 16 --handles 14 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 16 --handles 15 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 17 --handles 13 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 17 --handles 14 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 17 --handles 15 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 17 --handles 16 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 18 --handles 14 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 18 --handles 15 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 18 --handles 16 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 18 --handles 17 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 18 --handles 23 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 19 --handles 2 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 19 --handles 3 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 19 --handles 8 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 19 --handles 11 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 19 --handles 15 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 19 --handles 16 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 19 --handles 17 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 19 --handles 18 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 20 --handles 9 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 20 --handles 10 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 20 --handles 11 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 20 --handles 12 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 20 --handles 16 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 20 --handles 17 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 20 --handles 18 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 20 --handles 19 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 21 --handles 18 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 21 --handles 19 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 21 --handles 20 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 22 --handles 18 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 22 --handles 19 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 22 --handles 20 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 22 --handles 21 --test handle --pinv true --max-iter 200 --max-time inf
python3 pymanopt_test_karcher.py --manifold pB --optimize-from random --number 100 --dim 24 --ortho 23 --handles 22 --test handle --pinv true --max-iter 200 --max-time inf
